### ISSUE TITLE
Port SatBus3C0

### ISSUE THREAD

**Issue by rplauche** [openkosmosorg/KubOS#16]
Review / merge checklist:

- [x] Review new parent target (already exists, no pull request) [target-stm32f405-gcc](https://github.com/openkosmosorg/target-stm32f405-gcc)
- [x] Review new SatBus 3C0 target (already exists, no pull request) [target-na-satbus-3c0-gcc](https://github.com/openkosmosorg/target-na-satbus-3c0-gcc)
- [x] Review / merge openkosmosorg/cmsis-core-stm32f405rg#2
- [x] Review / merge openkosmosorg/target-stm32f405-pyboard-gcc#2, and rename repo to `target-pyboard-gcc`
- [x] Review / merge openkosmosorg/kubos-manifest#4
